name: Deploy to Heroku

on:
  push:
    branches:
      - main  # الفرع الذي تريد النشر منه (قد يكون "master" بدلاً من "main" في بعض المستودعات)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # إصدار Node.js الذي تستخدمه

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # إذا كان لديك سكربت build

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/your-heroku-app-name.git
          git push heroku main  # قد يكون "master" بدلاً من "main" في بعض المستودعات
